routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('help/{file}', 'admin\HelpController@index');

Route::resource('admin/home', 'admin\HomeController');
Route::resource('admin/', 'admin\HomeController');

Route::resource('admin/pages', 'admin\PageController');
Route::post('admin/pages/save-changes/', 'admin\PageController@save_changes');
Route::post('admin/pages/delete/', 'admin\PageController@remove');

Route::resource('admin/forms', 'admin\FormController');
Route::post('admin/forms/save-changes/', 'admin\FormController@save_changes');
Route::post('admin/forms/delete/', 'admin\FormController@remove');
Route::post('admin/forms/temp-store', 'admin\FormController@storeSession');
Route::get('admin/forms/create/{form_page_index?}', 'admin\FormController@create');
Route::get('admin/forms/{id}/edit/{page?}', 'admin\FormController@edit');
Route::get('admin/forms/remove-form/{page?}/{id?}', 'admin\FormController@removeForm');
Route::get('admin/forms/test/test', 'admin\FormController@testMode');
Route::get('admin/forms/add-page/{index}/{id?}', 'admin\FormController@addPage');
Route::get('admin/forms/submissions/{form_id}', 'admin\FormController@formSubmission');
Route::get('admin/forms/submissions/view/{id}', 'admin\FormController@submissionView');

Route::resource('admin/contents', 'admin\ContentController');
Route::post('admin/contents/save-changes/', 'admin\ContentController@save_changes');
Route::post('admin/contents/delete/', 'admin\ContentController@remove');
Route::post('admin/contents/find-n-replace', 'admin\ContentController@find_and_replace');
Route::post('admin/contents/sort/{field?}/{order?}', 'admin\ContentController@sort');

Route::resource('admin/files', 'admin\FileController');
Route::post('admin/files/save-changes/', 'admin\FileController@save_changes');
Route::post('admin/files/delete/', 'admin\FileController@remove');

Route::resource('admin/users', 'admin\UserController');
Route::post('admin/users/save-changes/', 'admin\UserController@save_changes');
Route::post('admin/users/delete/', 'admin\UserController@remove');

Route::resource('admin/events', 'admin\EventController');
Route::post('admin/events/save-changes/', 'admin\EventController@save_changes');
Route::post('admin/events/delete/', 'admin\EventController@remove');


Route::resource('admin/galleries', 'admin\GalleryController');
Route::post('admin/galleries/save-changes/', 'admin\GalleryController@save_changes');
Route::post('admin/galleries/delete/', 'admin\GalleryController@remove');
Route::get('admin/galleries/view/gallery/{id}/{i}', 'admin\GalleryController@view_gallery');

Route::get('files/image/{file_id}', 'PublicController@image');
Route::get('files/thumbnail/{file_id}', 'PublicController@thumbnail');
Route::get('files/doc/{file_id}/{download?}', 'PublicController@doc');
Route::get('page/{page_id?}', 'PublicController@page');
Route::get('public/testing', 'PublicController@testing');
Route::post('form/submit', 'PublicController@save_form');
Route::post('download_file', 'PublicController@download_file');
Route::get('search', 'PublicController@find_keyword');
Route::get('news-events', 'PublicController@news_events');
Route::get('news-events/{uri}', 'PublicController@news_events_view');

Route::get('/', 'PublicController@page');

Route::get('portal/{page_id?}', 'admin\PortalController@page');

/*Route::get('/', function () {
    return view('auth.login');
});*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-this',function(){
    //return \App\lib\MyMail::send('ram.abarquez.nettrac@gmail.com','Ramonito Aba', 'Calculus','body and soul');
});

resources/views/admin/page/create.blade.php
@extends('admin.main')

@section('content')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Pages</h1>
        <div class="btn-toolbar mb-2 mb-md-0"></div>

    </div>

    <div class="card">
        <div class="card-header">
            Create
        </div>
        <div class="card-body">
            <form style="margin-top: 10px" action="{{url('admin/pages')}}" method="post" class="needs-validation" novalidate>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group">
                    <label for="exampleFormControlInput1">Title</label>
                    <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="" required>
                    <div class="invalid-feedback">
                        Please add a title.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">URI</label>
                    <input type="text" class="form-control" name="uri" id="exampleFormControlInput2" placeholder="" value="/{{uniqid()}}" required>
                    <div class="invalid-feedback">
                        Please add a URI.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Head</label>
                    <textarea class="form-control" name="head"></textarea>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="page_state_id" value="1" checked="checked" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Publish
                    </label>
                </div>

                <div class="form-check" style="">
                    <input class="form-check-input" type="checkbox" name="private" value="1" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Is Private
                    </label>
                </div>

                <div class="form-group" style="margin-top: 20px">
                    {{--<label for="exampleFormControlInput1">Contents</label>
                    <input class="btn btn-info" type="button" value="Add/Remove Page Content" data-toggle="modal" data-target="#addContentModal">--}}

                    <div class="row" style="margin-bottom: 10px">
                        <div class="col">
                            <label for="exampleFormControlInput1">Contents</label>
                            <input class="btn btn-info" type="button" value="Add/Remove Page Content" data-toggle="modal" data-target="#addContentModal">
                        </div>
                    </div>


                    {{--<div class="card" style="width: 650px; margin-top: 15px">
                        <ul class="list-group list-group-flush" id="selected-content">
                        </ul>
                    </div>--}}

                    <div class="row">
                        <div class="card" style="/*width: 850px; margin-top: 15px*/" class="col col-5">
                            <ul class="list-group list-group-flush" id="selected-content">

                            </ul>
                        </div>
                    </div>


                </div>


                @include('admin.page.selectContent')



                <div class="float-lg-right" style="margin-bottom: 20px">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="#" id="back-button" class="btn btn-secondary">Back</a>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.main')

@section('content')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Pages</h1>
        <div class="btn-toolbar mb-2 mb-md-0"></div>

    </div>

    <div class="card">
        <div class="card-header">
            Edit
        </div>
        <div class="card-body">
            <form style="margin-top: 10px" action="{{url('admin/pages/save-changes')}}" method="post" class="needs-validation" novalidate>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="hidden" name="id" value="{{ $page->id }}">
                <div class="form-group">
                    <label for="exampleFormControlInput1">Title</label>
                    <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="" value="{{$page->title}}" required>
                    <div class="invalid-feedback">
                        Please add a title.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">URI</label>
                    <input type="text" class="form-control" name="uri" id="exampleFormControlInput2" placeholder="" value="{{$page->uri}}" required>
                    <div class="invalid-feedback">
                        Please add a title.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Head</label>
                    <textarea class="form-control" name="head">{{ $page->head }}</textarea>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="page_state_id" @if($page->page_state_id == 1) checked="checked" @endif value="1" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Published
                    </label>
                </div>

                <div class="form-check" style="">
                    <input class="form-check-input" type="checkbox" name="private" @if($page->private == 1) checked="checked" @endif value="1" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Is Private
                    </label>
                </div>

                <div class="form-group" style="margin-top: 20px">
                    <div class="row" style="margin-bottom: 10px">
                        <div class="col">
                            <label for="exampleFormControlInput1">Contents</label>
                            <input class="btn btn-info" type="button" value="Add/Remove Page Content" data-toggle="modal" data-target="#addContentModal">
                        </div>
                    </div>


                    <div class="row">
                        <div class="card" style="/*width: 850px; margin-top: 15px*/" class="col col-5">
                            <ul class="list-group list-group-flush" id="selected-content">
                                @if($page->page_content)
                                    @foreach($page->page_content as $v)
                                        <?php

                                        if($v->form_id){
                                            $type = 'Form';
                                            $title = $v->form->name;
                                            $content_id = $v->form_id;
                                            $order = $v->order;
                                            $input_name = 'form_id';
                                            $edit_link = url("admin/forms/{$v->form_id}/edit");
                                        }elseif($v->gallery_id){
                                            $type = 'Gallery';
                                            $title = $v->gallery->name;
                                            $content_id = $v->gallery_id;
                                            $order = $v->order;
                                            $input_name = 'gallery_id';
                                            $edit_link = url("admin/galleries/{$v->gallery_id}/edit");
                                        }else{
                                            $type = $v->content->content_type->name;
                                            $title = $v->content->title;
                                            $content_id = $v->content_id;
                                            $order = (!in_array($v->content->content_type->name,['Footer','Header']))?$v->order:"";
                                            $input_name = 'content_id';
                                            $edit_link = url("admin/contents/{$v->content_id}/edit");
                                        }

                                        ?>
                                        <li class="list-group-item">
                                            <div class="row">
                                                <div class="col col-lg-10">
                                                    <div class="input-group mb-3">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text" style="width: 79px">{{ $type }}</span>
                                                            <span class="input-group-text" style="width: 473px">{{ $title }}</span>
                                                        </div>
                                                        <input type="hidden" name="{{$input_name}}[]" value="{{ $content_id }}">
                                                        <input type="number" name="content_order[]" class="form-control" value="{{ $order }}" aria-label="" placeholder="">

                                                    </div>
                                                </div>
                                                <div class="col col-lg-1">
                                                    @if(!in_array($type,['Header','Footer']))
                                                        <a href="{{$edit_link}}" target="_blank" class="float-left">
                                                            <svg class="feather feather-edit-3 sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-reactid="496"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>
                                                        </a>
                                                    @endif
                                                </div>
                                            </div>
                                        </li>
                                    @endforeach
                                @endif
                            </ul>
                        </div>
                    </div>
                </div>


                @include('admin.page.selectContent')

                <div class="float-lg-right" style="margin-bottom: 20px">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="#" id="back-button" class="btn btn-secondary">Back</a>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/page/list.blade.php
@extends('admin.main')

@section('content')

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Pages</h1>
        <div class="btn-toolbar mb-2 mb-md-0"></div>

    </div>

    <nav class="navbar-expand-lg" size="" style="padding: 5px 0">
        <a class="btn btn-primary" href="{{url('admin/pages/create')}}">Create</a>

        @include('admin.search')

    </nav>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>

                {!! html_entity_decode($header) !!}
                <th style="text-align: center !important;">Action</th>
            </tr>
            </thead>
            <tbody>
            @if(\App\Model\Page::count() > 0)
                @foreach($rec as $row)
                    <tr>
                        <td>{{$row->title}}</td>
                        <td>{{$row->uri}}</td>
                        <td>{{$row->user->name}}</td>
                        <td>{{$row->page_state->name}}</td>
                        <td>{{$row->created_at}}</td>
                        <td>{{$row->updated_at}}</td>
                        <td align="center">
                            <a href="{{ route('pages.edit',$row->id)}}">
                                <svg class="feather feather-edit sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-reactid="501"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                            </a>
                            <a href="{{ url('admin/pages/delete')  }}" data-id="{{ $row->id }}" class="delete-this">
                                <svg class="feather feather-delete sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-reactid="461"><path d="M21 4H8l-7 8 7 8h13a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z"></path><line x1="18" y1="9" x2="12" y2="15"></line><line x1="12" y1="9" x2="18" y2="15"></line></svg>
                            </a>

                            <a href="/{{ (($row->private)?"portal":"page").$row->uri  }}" data-id="{{ $row->id }}" class="view-this" target="_blank">
                                <svg data-v-6f720bf2="" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon-svg feather feather-eye"><path data-v-6f720bf2="" d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle data-v-6f720bf2="" cx="12" cy="12" r="3"></circle></svg>
                            </a>

                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>


        </table>
    </div>

    <div>
        {{$rec->links('vendor.pagination.bootstrap-4')}}
    </div>

@endsection

resources/views/admin/page/selectContent.blade.php
<!-- Modal -->
<div class="modal fade" id="addContentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Select Contents</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <?php
            $checked = 'checked="checked"';
            $headerS = $checked;
            $footerS = $checked;

            if(isset($selected_contents) && is_array($selected_contents)){
                $headerS = '';
                $footerS = '';
            }else{
                $selected_contents = [];
                $selected_forms = [];
                $selected_galleries = [];
            }
            ?>

            <div class="modal-body" style="max-height: 500px; overflow-y: scroll">

                <ul>
                    <li>
                        Header
                        <ul>
                            @if(count($contents) > 0 && isset($contents['Header']))
                                @foreach($contents['Header'] as $header)
                                    <li>
                                        <div class="">
                                            <input class="form-check-input" type="checkbox" {{$headerS}} name="content[]" id="" {{ (in_array($header->id,$selected_contents))?$checked:"" }} value="{{$header->id}}" data-contenttype="Header" data-title="{{$header->title}}">
                                            <label class="custom-control-label" for="customCheck1">{{ $header->title }}</label>
                                        </div>
                                    </li>
                                    <?php $headerS = ''?>
                                @endforeach
                            @endif

                        </ul>
                    </li>
                    <li>
                        Footer
                        <ul>
                            @if(count($contents) > 0 && isset($contents['Footer']))
                                @foreach($contents['Footer'] as $header)
                                    <li>
                                        <div class="">
                                            <input class="form-check-input" type="checkbox" {{$footerS}} name="content[]" id="" {{ (in_array($header->id,$selected_contents))?$checked:"" }} value="{{$header->id}}" data-contenttype="Footer" data-title="{{$header->title}}">
                                            <label class="custom-control-label" for="customCheck1">{{ $header->title }}</label>
                                        </div>
                                    </li>
                                    <?php $footerS = ''?>
                                @endforeach
                            @endif

                        </ul>
                    </li>
                    <li>
                        Inner Content
                        <ul>
                            @if(count($contents) > 0 && isset($contents['Inner']))
                                @foreach($contents['Inner'] as $header)
                                    <li>
                                        <div class="">
                                            <input class="form-check-input" type="checkbox" name="content[]" id="" {{ (in_array($header->id,$selected_contents))?$checked:"" }} value="{{$header->id}}" data-contenttype="Inner" data-title="{{$header->title}}">
                                            <label class="custom-control-label" for="customCheck1">{{ $header->title }}</label>
                                        </div>
                                    </li>
                                @endforeach
                            @endif

                        </ul>
                    </li>
                    <li>
                        Forms
                        <ul>
                            @if($forms)
                                @foreach($forms as $form)
                                    <li>
                                        <div class="">
                                            <input class="form-check-input" type="checkbox" name="form[]" id="" {{ (in_array($form->id,$selected_forms))?$checked:"" }} value="{{$form->id}}" data-contenttype="Form" data-title="{{$form->name}}">
                                            <label class="custom-control-label" for="customCheck1">{{ $form->name }}</label>
                                        </div>
                                    </li>
                                @endforeach
                            @endif

                        </ul>
                    </li>

                    <li>
                        Galleries
                        <ul>
                            @if($galleries)
                                @foreach($galleries as $gallery)
                                    <li>
                                        <div class="">
                                            <input class="form-check-input" type="checkbox" name="gallery[]" id="" {{ (in_array($gallery->id,$selected_galleries))?$checked:"" }} value="{{$gallery->id}}" data-contenttype="Gallery" data-title="{{$gallery->name}}">
                                            <label class="custom-control-label" for="customCheck1">{{ $gallery->name }}</label>
                                        </div>
                                    </li>
                                @endforeach
                            @endif

                        </ul>
                    </li>
                </ul>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="add-contents">Save changes</button>
            </div>
        </div>
    </div>
</div>