routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('help/{file}', 'admin\HelpController@index');

Route::resource('admin/home', 'admin\HomeController');
Route::resource('admin/', 'admin\HomeController');

Route::resource('admin/pages', 'admin\PageController');
Route::post('admin/pages/save-changes/', 'admin\PageController@save_changes');
Route::post('admin/pages/delete/', 'admin\PageController@remove');

Route::resource('admin/forms', 'admin\FormController');
Route::post('admin/forms/save-changes/', 'admin\FormController@save_changes');
Route::post('admin/forms/delete/', 'admin\FormController@remove');
Route::post('admin/forms/temp-store', 'admin\FormController@storeSession');
Route::get('admin/forms/create/{form_page_index?}', 'admin\FormController@create');
Route::get('admin/forms/{id}/edit/{page?}', 'admin\FormController@edit');
Route::get('admin/forms/remove-form/{page?}/{id?}', 'admin\FormController@removeForm');
Route::get('admin/forms/test/test', 'admin\FormController@testMode');
Route::get('admin/forms/add-page/{index}/{id?}', 'admin\FormController@addPage');
Route::get('admin/forms/submissions/{form_id}', 'admin\FormController@formSubmission');
Route::get('admin/forms/submissions/view/{id}', 'admin\FormController@submissionView');

Route::resource('admin/contents', 'admin\ContentController');
Route::post('admin/contents/save-changes/', 'admin\ContentController@save_changes');
Route::post('admin/contents/delete/', 'admin\ContentController@remove');
Route::post('admin/contents/find-n-replace', 'admin\ContentController@find_and_replace');
Route::post('admin/contents/sort/{field?}/{order?}', 'admin\ContentController@sort');

Route::resource('admin/files', 'admin\FileController');
Route::post('admin/files/save-changes/', 'admin\FileController@save_changes');
Route::post('admin/files/delete/', 'admin\FileController@remove');

Route::resource('admin/users', 'admin\UserController');
Route::post('admin/users/save-changes/', 'admin\UserController@save_changes');
Route::post('admin/users/delete/', 'admin\UserController@remove');

Route::resource('admin/events', 'admin\EventController');
Route::post('admin/events/save-changes/', 'admin\EventController@save_changes');
Route::post('admin/events/delete/', 'admin\EventController@remove');


Route::resource('admin/galleries', 'admin\GalleryController');
Route::post('admin/galleries/save-changes/', 'admin\GalleryController@save_changes');
Route::post('admin/galleries/delete/', 'admin\GalleryController@remove');
Route::get('admin/galleries/view/gallery/{id}/{i}', 'admin\GalleryController@view_gallery');

Route::get('files/image/{file_id}', 'PublicController@image');
Route::get('files/thumbnail/{file_id}', 'PublicController@thumbnail');
Route::get('files/doc/{file_id}/{download?}', 'PublicController@doc');
Route::get('page/{page_id?}', 'PublicController@page');
Route::get('public/testing', 'PublicController@testing');
Route::post('form/submit', 'PublicController@save_form');
Route::post('download_file', 'PublicController@download_file');
Route::get('search', 'PublicController@find_keyword');
Route::get('news-events', 'PublicController@news_events');
Route::get('news-events/{uri}', 'PublicController@news_events_view');

Route::get('/', 'PublicController@page');

Route::get('portal/{page_id?}', 'admin\PortalController@page');

/*Route::get('/', function () {
    return view('auth.login');
});*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-this',function(){
    //return \App\lib\MyMail::send('ram.abarquez.nettrac@gmail.com','Ramonito Aba', 'Calculus','body and soul');
});

app/Http/Controllers/admin/ContentController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Request;
use App\Http\Controllers\Controller;

class ContentController extends Controller
{
    private $sort_field = 'title';
    private $sort_order = 'asc';
    private $main_table = 'contents';
    private $controller = 'contents';
    private $view_folder = 'content';
    private $mgt_name = 'Contents';

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $keyword = Request::get('keyword');

        $where = "1";

        $session_keyword_key = "{$this->controller}.keyword";


        if(Request::has('keyword') || Request::get('keyword')){
            $keyword = Request::get('keyword');
            Request::session()->put($session_keyword_key, $keyword);
        }elseif(Request::session()->get($session_keyword_key)){
            $keyword = Request::session()->get($session_keyword_key);
        }

        if($keyword){
            $where = "contents.title LIKE '%{$keyword}%' ";
        }

        $config = [
            'controller' => $this->controller,
            'sort_header' => [
                'title' => ['Title', 'asc', ''],
                'content_types.name' => ['Type', 'asc', ''],
                'users.name' => ['Created by', 'asc', ''],
                'contents.created_at' => ['Created at', 'asc', ''],
                'contents.updated_at' => ['Updated at', 'asc', '']
            ]
        ];

        $sorter = new \App\Lib\Sorter($config, $this->sort_field, $this->sort_order);

        $res = \App\Model\Content::orderBy($this->sort_field, $this->sort_order)
            ->join('content_types', 'contents.content_type_id','=','content_types.id')
            ->join('users', 'contents.user_id','=','users.id')
            ->select('contents.*')
            ->whereRaw($where)
            ->paginate(env('ADMIN_PAGE_LIMIT'));

        //p($res[0]->pages(),1);

        $data = [
            'rec' => $res,
            'sort_field' => $this->sort_field,
            'sort_order' => $this->sort_order,
            'header' => $sorter->getHeader(),
            'controller' => $this->controller,
            'mgt_name' => $this->mgt_name,
            'keyword' => $keyword
        ];

        return view('admin.'.$this->view_folder.'.list',$data);
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.'.$this->view_folder.'.create',['mgt_name' => $this->mgt_name]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $obj = new \App\Model\Content();

        $obj->title = Request::input('title');
        $obj->content_type_id = Request::input('content_type_id');
        $obj->content = Request::input('content');
        $obj->user_id = Auth::id();

        $obj->save();

        return redirect('admin/' . $this->controller)->with('success', config('app.alert_messages.save_success'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $obj = \App\Model\Content::find($id);

        //p($content->title);

        return view('admin.content.edit',['content' => $obj]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        p($id);

        //
        return 'you';
        //p(Request::get('title'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

    }

    public function save_changes(){
        $id = Request::input('id');
        $message = config('app.alert_messages.record_not_found');
        $content = \App\Model\Content::find($id);

        if(isset($content->id) && $content->id){
            $content->title = Request::input('title');
            $content->content = Request::input('content');
            $content->content_type_id = Request::input('content_type_id');
            $content->save();
            $message = config('app.alert_messages.update_success');
        }


        return redirect('/admin/' . $this->controller)->with('success', $message);
    }

    public function find_and_replace(){
        $find = Request::input('find');
        $action = Request::input('action');
        $replacement = Request::input('replacement');
        $message = "";

        $result = \App\Model\Content::where('content', 'LIKE', "%{$find}%")->get();

        if($result && $action == 'find'){

            $message .= '<span> The following content(s) contain\'s the substring "'.$find.'"<span><ul>';
            foreach ($result as $row){
                $message .= '<li>'.$row->title.'</li>';
            }
            $message .= '</ul>';
        }

        if($result && $action == 'replace'){
            $message .= '<span>The following content(s) was updated<span><ul>';
            foreach ($result as $row){
                $message .= '<li>'.$row->title.'</li>';
                \DB::table($this->main_table)
                    ->where('id',$row->id)
                    ->update(['content' => str_replace($find,$replacement,$row->content)]);
            }
            $message .= '</ul>';
        }

        return redirect('/admin/' . $this->controller)->with('success', $message);
    }

    public function remove(){

        $content =  \App\Model\Content::find(Request::input('id'));
        $message = config('app.alert_messages.record_not_found');
        if(isset($content->id) && $content->id){
            $content->delete();
            $message = config('app.alert_messages.delete_success');
        }

        return redirect('/admin/' . $this->controller)->with('success', $message);
    }
}

resources/views/admin/content/create.blade.php
@extends('admin.main')

@section('content')

    <style>


    </style>



    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Contents</h1>
        <div class="btn-toolbar mb-2 mb-md-0"></div>

    </div>

    <div class="card">
        <div class="card-header">
            Create
        </div>
        <div class="card-body">
            <form style="margin-top: 10px" action="{{url('admin/contents')}}" method="post" class="needs-validation" novalidate>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group">
                    <label for="exampleFormControlInput1">Title</label>
                    <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="" autocomplete="off" required>


                    <div class="invalid-feedback">
                        Please add a title.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Type</label>
                    <select id="inputState" name="content_type_id" class="form-control">
                        @foreach(\App\Model\ContentType::all() as $contentType)
                            <option value="{{ $contentType->id }}" @if($contentType->name == 'Inner') selected="selected" @endif>{{ $contentType->name }}</option>
                        @endforeach

                    </select>
                    <div class="invalid-feedback">
                        Please select a type.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Content</label>
                    <textarea class="form-control" id="content" name="content" rows="3" style="" required></textarea>
                    <div class="invalid-feedback">
                        Please add a content.
                    </div>
                </div>

                <div class="float-lg-right" style="margin-bottom: 20px">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="#" id="back-button" class="btn btn-secondary">Back</a>
                </div>

            </form>
        </div>
    </div>

    @include('admin.tiny')

@endsection

resources/views/admin/content/edit.blade.php
@extends('admin.main')

@section('content')



    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Contents</h1>
        <div class="btn-toolbar mb-2 mb-md-0"></div>

    </div>

    <div class="card">
        <div class="card-header">
            Edit
        </div>
        <div class="card-body">
            <form style="margin-top: 10px" action="{{url('admin/contents/save-changes')}}" method="post" class="needs-validation" novalidate>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="hidden" name="id" value="{{ $content->id }}">
                <div class="form-group">
                    <label for="exampleFormControlInput1">Title</label>
                    <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="" value="{{ $content->title }}" required>
                    <div class="invalid-feedback">
                        Please add a title.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Type</label>
                    <select id="inputState" name="content_type_id" class="form-control">
                        @foreach(\App\Model\ContentType::all() as $contentType)
                            <option value="{{ $contentType->id }}" @if($contentType->id == $content->content_type_id) selected="selected" @endif>{{ $contentType->name }}</option>
                        @endforeach

                    </select>
                    <div class="invalid-feedback">
                        Please select a type.
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Content</label>
                    <textarea class="form-control" id="content" name="content" rows="3" required>{{ $content->content }}</textarea>
                    <div class="invalid-feedback">
                        Please add a content.
                    </div>
                </div>

                <div class="float-lg-right" style="margin-bottom: 20px">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="#" id="back-button" class="btn btn-secondary">Back</a>
                </div>
            </form>
        </div>
    </div>

    @include('admin.tiny')

@endsection

resources/views/admin/content/findnreplace.blade.php
<!-- Modal -->
<div class="modal fade" id="findnreplace_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="">
                <h5 class="modal-title" id="exampleModalLabel">Find and replace a string</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form method="post" action="/admin/contents/find-n-replace">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Find string</label>
                        <input type="text" name="find" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required>

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Replacement string</label>
                        <input type="text" class="form-control" name="replacement" id="exampleInputPassword1" placeholder="" required>
                    </div>
                    <input type="hidden" name="action" id="action" value="">
                    <button type="submit" class="btn btn-primary" id="replace" style="display: none">Submit</button>
                </form>

            </div>
            <div class="modal-footer" style="">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="find">Find</button>
                <button type="button" class="btn btn-primary" id="find_and_replace">Find and Replace</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $("#find").on('click',function(){
            $("#action").val('find');
            $("#exampleInputPassword1").removeAttr('required');
            $("#replace").click();
        });

        $("#find_and_replace").on('click',function(){
            $("#action").val('replace');
            $("#exampleInputPassword1").attr('required','required');
            $("#replace").click();
        });
    });
</script>

resources/views/admin/content/list.blade.php
@extends('admin.main')

@section('content')
    @include('admin.content.findnreplace')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Contents</h1>
        <div class="btn-toolbar mb-2 mb-md-0"></div>

    </div>

    <nav class="navbar-expand-lg" size="" style="padding: 5px 0">
        <a class="btn btn-primary" href="{{url('admin/contents/create')}}">Create</a>
        <input class="btn btn-primary" type="button" value="find and replace" data-toggle="modal" data-target="#findnreplace_modal">

        @include('admin.search')
    </nav>



    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>

                {!! html_entity_decode($header) !!}
                <th style="text-align: center !important;">Action</th>
            </tr>
            </thead>
            <tbody>
                @if(\App\Model\Content::count() > 0)
                    @foreach($rec as $row)
                        <tr>
                            <td>{{$row->title}}</td>
                            <td>{{$row->content_type->name}}</td>
                            <td>{{$row->user->name}}</td>
                            <td>{{$row->created_at}}</td>
                            <td>{{$row->updated_at}}</td>
                            <td align="center">
                                <a href="{{ route('contents.edit',$row->id)}}">
                                    <svg class="feather feather-edit sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-reactid="501"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                                </a>
                                <a href="{{ url('admin/contents/delete')  }}" data-id="{{ $row->id }}" class="delete-this">
                                    <svg class="feather feather-delete sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" data-reactid="461"><path d="M21 4H8l-7 8 7 8h13a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z"></path><line x1="18" y1="9" x2="12" y2="15"></line><line x1="12" y1="9" x2="18" y2="15"></line></svg>
                                </a>

                            </td>
                        </tr>
                    @endforeach
                @endif

            </tbody>


        </table>
    </div>

    <div>
        {{$rec->links('vendor.pagination.bootstrap-4')}}
    </div>




@endsection